### ISSUE TITLE
Google form with mandatory "development activities" group, thus preventing to correctly declare new tools when this group doesn't apply.

### ISSUE THREAD

**Issue by GenEars** [achiminator/SW-Tool-Hub#5]
Dear semantic-tool-hub team, the Google form currently has a mandatory "development activities" group, thus preventing to correctly declare new tools when this category group doesn't apply.

For example, I have declared the [Graphameleon](https://github.com/Orange-OpenSource/graphameleon) tool this morning using the form-based approach. This tool matches a category in the "Deployment activities". However, when submitting the form, the form validation forced me to add a "development activities" category (I used the "other" field to overcome this although it is not relevant).

So, could you update the validation of the form-based approach for easier declaration of tools?

**Comment by nandana** [comment]
@GenEars Thanks a lot for pointing this out. None of those group should have been mandatory. I have fixed it in form now.
